import type { NextConfig } from "next";
import { withSerwist } from "@serwist/turbopack";
import createNextIntlPlugin from "next-intl/plugin";
import pkg from "./package.json";
import { assertMockAuthNotInProduction } from "./lib/auth/mockAuth";

// SECURITY: fail the build loudly if the test-only mock-auth seam (issue #751)
// is enabled in a production build. The seam is already inert in production
// (isMockAuthEnabled() short-circuits on NODE_ENV), so this is defence-in-depth
// — it turns a silent misconfiguration into a hard build failure.
assertMockAuthNotInProduction();

const nextConfig: NextConfig = {
  cacheComponents: true,
  // The FSRS optimizer route loads @open-spaced-repetition/binding which
  // ships a native Node.js binary (.node). Mark it (and its platform-specific
  // sub-package) as server-external so Next.js/Turbopack does not attempt to
  // bundle them — they are loaded at runtime by Node's native addon loader.
  serverExternalPackages: [
    "@open-spaced-repetition/binding",
    "@open-spaced-repetition/binding-android-arm64",
    "@open-spaced-repetition/binding-darwin-arm64",
    "@open-spaced-repetition/binding-darwin-x64",
    "@open-spaced-repetition/binding-linux-arm64-gnu",
    "@open-spaced-repetition/binding-linux-arm64-musl",
    "@open-spaced-repetition/binding-linux-x64-gnu",
    "@open-spaced-repetition/binding-linux-x64-musl",
    "@open-spaced-repetition/binding-wasm32-wasi",
    "@open-spaced-repetition/binding-win32-arm64-msvc",
    "@open-spaced-repetition/binding-win32-ia32-msvc",
    "@open-spaced-repetition/binding-win32-x64-msvc",
  ],
  env: {
    NEXT_PUBLIC_APP_VERSION: pkg.version ?? "dev",
  },
  // /whats-new reads CHANGELOG.md via fs at render time. The path is dynamic
  // (process.cwd() + filename), which @vercel/nft may not statically trace —
  // include it explicitly so the file ships with the deployment in any
  // output mode.
  outputFileTracingIncludes: {
    "/whats-new": ["./CHANGELOG.md"],
  },
  images: {
    // Custom loader routes sprite paths to pre-generated static WebP files,
    // bypassing the /_next/image optimisation endpoint entirely. GitHub avatar
    // URLs (user-controlled) are passed through unchanged.
    // See lib/sprites/imageLoader.ts for the full routing logic.
    loader: "custom",
    loaderFile: "./lib/sprites/imageLoader.ts",
    // Constrain deviceSizes and imageSizes so their union exactly equals the
    // set of widths pre-generated by `npm run seed:sprites`. The loader snaps
    // any incoming width to the nearest generated width, so Next.js will only
    // ever request widths from this list.
    // Generated widths (from lib/sprites/imageLoaderHelpers.ts):
    //   32, 40, 48, 56, 64, 120, 150, 180, 192, 320
    // Split across deviceSizes (larger) and imageSizes (smaller) as Next.js
    // requires deviceSizes ≥ imageSizes values; the union is what matters.
    deviceSizes: [150, 180, 192, 320],
    imageSizes: [32, 40, 48, 56, 64, 120],
    remotePatterns: [
      {
        // Defence-in-depth: keep the remotePatterns entry for GitHub avatars
        // so the intent is explicit even though remotePatterns is not enforced
        // at runtime when a custom loader is set.
        protocol: "https",
        hostname: "avatars.githubusercontent.com",
      },
    ],
  },
};

// `withSerwist` keeps Next.js 16's default Turbopack in place (no `--webpack`
// regression) and marks the esbuild bundler used by the service-worker route
// (`app/sw/[path]/route.ts`) as server-external so Turbopack does not try to
// bundle it. Offline support for the installed PWA — see issue #703.
//
// `withNextIntl` wraps the config so next-intl can wire up its server-side
// request config (i18n/request.ts) and message imports without the
// "Couldn't find next-intl config" runtime error (#1260).
const withNextIntl = createNextIntlPlugin("./i18n/request.ts");
export default withNextIntl(withSerwist(nextConfig));
