import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";
import { withSentryConfig } from "@sentry/nextjs";
import pkg from "./package.json";
import { assertMockAuthNotInProduction } from "./lib/auth/mockAuth";

// SECURITY: fail the build loudly if the test-only mock-auth seam (issue #751)
// is enabled in a production build. The seam is already inert in production
// (isMockAuthEnabled() short-circuits on NODE_ENV), so this is defence-in-depth
// — it turns a silent misconfiguration into a hard build failure.
assertMockAuthNotInProduction();

const nextConfig: NextConfig = {
  cacheComponents: true,
  // The FSRS optimizer route loads @open-spaced-repetition/binding which
  // ships a native Node.js binary (.node). Mark it (and its platform-specific
  // sub-package) as server-external so Next.js/Turbopack does not attempt to
  // bundle them — they are loaded at runtime by Node's native addon loader.
  serverExternalPackages: [
    "@open-spaced-repetition/binding",
    "@open-spaced-repetition/binding-android-arm64",
    "@open-spaced-repetition/binding-darwin-arm64",
    "@open-spaced-repetition/binding-darwin-x64",
    "@open-spaced-repetition/binding-linux-arm64-gnu",
    "@open-spaced-repetition/binding-linux-arm64-musl",
    "@open-spaced-repetition/binding-linux-x64-gnu",
    "@open-spaced-repetition/binding-linux-x64-musl",
    "@open-spaced-repetition/binding-wasm32-wasi",
    "@open-spaced-repetition/binding-win32-arm64-msvc",
    "@open-spaced-repetition/binding-win32-ia32-msvc",
    "@open-spaced-repetition/binding-win32-x64-msvc",
  ],
  env: {
    NEXT_PUBLIC_APP_VERSION: pkg.version ?? "dev",
  },
  // /whats-new reads CHANGELOG.md via fs at render time. The path is dynamic
  // (process.cwd() + filename), which @vercel/nft may not statically trace —
  // include it explicitly so the file ships with the deployment in any
  // output mode.
  //
  // The service worker is NO LONGER a route: it is built to a static
  // `public/sw/sw.js` asset by `scripts/build-sw.mjs` (post-`next build`) and
  // served by Vercel's CDN, so there is no serverless function and therefore
  // no file-trace gap to patch (the previous `/sw/[path]` entry that forced
  // `next/dist/server/config.js` into the function bundle is gone, #1752,
  // superseding the #1751 hotfix for #1749).
  outputFileTracingIncludes: {
    "/whats-new": ["./CHANGELOG.md"],
  },
  // Headers for the statically-generated service-worker script (built to
  // public/sw/ by scripts/build-sw.mjs).
  //
  // - `Cache-Control: no-cache` - the SW spec requires the browser to always
  //   revalidate the worker script before deciding whether to install a new
  //   version; without it, a future edge-cache change could silently freeze
  //   updates for all installed PWAs (#1749).
  // - `Service-Worker-Allowed: /` - the worker is registered from /sw/sw.js but
  //   must claim the whole-site scope "/". The Route Handler previously set this
  //   header itself; for the static asset it is applied here.
  async headers() {
    return [
      {
        source: "/sw/sw.js",
        headers: [
          { key: "Cache-Control", value: "no-cache" },
          { key: "Service-Worker-Allowed", value: "/" },
        ],
      },
      {
        source: "/sw/sw.js.map",
        headers: [{ key: "Cache-Control", value: "no-cache" }],
      },
    ];
  },
  images: {
    // Custom loader routes sprite paths to pre-generated static WebP files,
    // bypassing the /_next/image optimisation endpoint entirely. GitHub avatar
    // URLs (user-controlled) are passed through unchanged.
    // See lib/sprites/imageLoader.ts for the full routing logic.
    loader: "custom",
    loaderFile: "./lib/sprites/imageLoader.ts",
    // Constrain deviceSizes and imageSizes so their union exactly equals the
    // set of widths pre-generated by `npm run seed:sprites`. The loader snaps
    // any incoming width to the nearest generated width, so Next.js will only
    // ever request widths from this list.
    // Generated widths (from lib/sprites/imageLoaderHelpers.ts):
    //   32, 40, 48, 56, 64, 120, 150, 180, 192, 320
    // Split across deviceSizes (larger) and imageSizes (smaller) as Next.js
    // requires deviceSizes ≥ imageSizes values; the union is what matters.
    deviceSizes: [150, 180, 192, 320],
    imageSizes: [32, 40, 48, 56, 64, 120],
    remotePatterns: [
      {
        // Defence-in-depth: keep the remotePatterns entry for GitHub avatars
        // so the intent is explicit even though remotePatterns is not enforced
        // at runtime when a custom loader is set.
        protocol: "https",
        hostname: "avatars.githubusercontent.com",
      },
    ],
  },
};

// The Serwist service worker is no longer built through a Next.js Route
// Handler, so the `withSerwist` wrapper (which only marked esbuild/esbuild-wasm
// as server-external for that route) is gone. The worker is now bundled to a
// static `public/sw/sw.js` asset by `scripts/build-sw.mjs` after `next build`.
// Offline support for the installed PWA is unchanged, see issues #703, #1752.
//
// `withNextIntl` wraps the config so next-intl can wire up its server-side
// request config (i18n/request.ts) and message imports without the
// "Couldn't find next-intl config" runtime error (#1260).
const withNextIntl = createNextIntlPlugin("./i18n/request.ts");

// `withSentryConfig` is the outermost wrapper so it sees the final config,
// including next-intl's additions, when it adds its Turbopack settings and
// build hook. Wrapping order: Sentry(next-intl(nextConfig)).
//
// Key options:
//   silent           - suppresses Sentry CLI output during `next build`.
//   sourcemaps.deleteSourcemapsAfterUpload
//                    - strips source maps from the build output after they are
//                      uploaded so they are not served publicly. Defaults to
//                      true in v10; set explicitly for clarity.
//   widenClientFileUpload - disabled; we do not need to upload additional
//                      client files beyond the standard Next.js output.
//   tunnelRoute      - proxies Sentry events through /monitoring so ad-blocker
//                      extensions cannot block the DSN endpoint. Serwist
//                      runtimeCaching only intercepts GET requests, so POST
//                      requests to /monitoring bypass the service-worker cache
//                      matcher entirely and reach the server unaltered.
//   org / project    - read from env; build-time only (not shipped to browser).
//
// BUNDLER: the build uses Turbopack, which is what a plain `next build` runs on
// Next 16 (package.json passes no `--webpack` flag). Under Turbopack,
// withSentryConfig uploads source maps from a
// `compiler.runAfterProductionCompile` hook that it installs by default, so no
// webpack plugin is involved; the upload runs only when SENTRY_AUTH_TOKEN is
// set (see below). Options under the `webpack` key of the Sentry options do
// nothing under this build and nothing warns about them, so do not add any:
// use a Turbopack-aware Sentry option or `nextConfig` instead.
// lib/observability/nextConfigSentry.test.ts fails if one is added.
//
// DEBUG LOGGING: the Sentry SDK's debug-logging code still ships in the
// bundle. `webpack.treeshake.removeDebugLogging` was removed because it did
// nothing under Turbopack (#2076), and @sentry/nextjs had no Turbopack
// equivalent as of 10.65.0 (re-check when upgrading it): Sentry's tree-shaking
// guide says those options are not supported for Turbopack builds. Defining `__SENTRY_DEBUG__` through `compiler.define`
// is not a proven substitute, because the SDK checks
// `typeof __SENTRY_DEBUG__`, and it is unconfirmed whether Turbopack rewrites a
// `typeof` check for a user define. The code only logs when `debug: true` is
// passed to Sentry.init, which no instrumentation file does, so today the cost
// is bundle size only.
//
// INERT WITHOUT SECRETS: When NEXT_PUBLIC_SENTRY_DSN is not set, Sentry.init
// is a no-op (no network, no throw). When SENTRY_AUTH_TOKEN is absent,
// withSentryConfig warns and skips map upload - it does NOT fail the build.
export default withSentryConfig(withNextIntl(nextConfig), {
  silent: true,
  sourcemaps: {
    deleteSourcemapsAfterUpload: true,
  },
  widenClientFileUpload: false,
  tunnelRoute: "/monitoring",
  org: process.env.SENTRY_ORG,
  project: process.env.SENTRY_PROJECT,
});
