// Phonetic overrides for the Web Speech API "Hear name" button. Keys are
// lower-cased Pokémon display names; values are respellings that the default
// en-GB system voices (Apple's Daniel on macOS/iOS, Google UK English on
// Chrome/Android) pronounce noticeably better than the raw name. The list is
// deliberately conservative — only entries whose default rendering is clearly
// wrong are worth carrying.
const OVERRIDES: Record<string, string> = {
  // Orthographic curveballs: hyphens, apostrophes, accents, special glyphs,
  // missing letters. The synth otherwise parses these as separators / errors.
  "nidoran♀": "nidoran female",
  "nidoran♂": "nidoran male",
  "farfetch’d": "farfetched",
  "farfetch'd": "farfetched",
  "sirfetch’d": "sir fetched",
  "sirfetch'd": "sir fetched",
  "type: null": "type null",
  flabébé: "flah bay bay",
  feraligatr: "feral i gay tor",
  qwilfish: "kwill fish",
  overqwil: "oh ver kwil",
  porygon2: "porygon two",
  "porygon-z": "porygon zee",
  "ho-oh": "ho oh",
  "jangmo-o": "jang mo oh",
  "hakamo-o": "ha ka mo oh",
  "kommo-o": "kom mo oh",
  "tapu koko": "tah poo koh koh",
  "tapu lele": "tah poo lay lay",
  "tapu bulu": "tah poo boo loo",
  "tapu fini": "tah poo fee nee",

  // The "tw" digraph trips most synths.
  mewtwo: "mew two",

  // "qua" → /kw/ is consistently mangled.
  rayquaza: "ray kwah zuh",
  araquanid: "uh rak wah nid",

  // Eeveelutions: the "-eon" suffix routinely gets read as a single syllable.
  vaporeon: "vay por ee on",
  jolteon: "jolt ee on",
  flareon: "flair ee on",
  espeon: "es pee on",
  umbreon: "um bree on",
  leafeon: "leaf ee on",
  glaceon: "glay see on",
  sylveon: "sil vee on",

  // Kanto.
  caterpie: "ca ter pee",
  pidgeotto: "pid jee ot oh",
  pidgeot: "pid jee ot",
  rattata: "rat tat ah",
  dugtrio: "dug tree oh",
  growlithe: "growl ith",
  machop: "ma chop",
  machoke: "ma choke",
  machamp: "ma champ",
  victreebel: "vic tree bell",
  geodude: "jee oh dude",
  doduo: "doh doo oh",
  dodrio: "doh dree oh",
  exeggcute: "egg ze cute",
  exeggutor: "egg ze cu tor",
  lickitung: "lick ee tung",
  kangaskhan: "kang us kahn",
  gyarados: "gah ruh dose",
  porygon: "por ih gon",
  omanyte: "oh ma nite",
  omastar: "oh ma star",
  kabutops: "kab oo tops",
  aerodactyl: "air oh dac til",
  articuno: "ar ti koo no",
  zapdos: "zap dose",
  moltres: "mole tres",

  // Johto.
  cyndaquil: "sin duh kwill",
  typhlosion: "tie flow zhun",
  ariados: "air ee a dose",
  xatu: "zah too",
  ampharos: "am fa ros",
  sudowoodo: "soo doh woo doh",
  politoed: "pol ee toad",
  quagsire: "kwag sire",
  misdreavus: "miss dree vus",
  unown: "un own",
  wobbuffet: "wob buh fay",
  girafarig: "ji raf uh rig",
  teddiursa: "teh dee ur sa",
  mantine: "man teen",
  phanpy: "fan pee",
  tyrogue: "tie rog",
  raikou: "rye koo",
  entei: "en tay",
  suicune: "swee koon",
  tyranitar: "tie ran i tar",
  lugia: "loo gee uh",
  celebi: "sel uh bee",

  // Hoenn.
  sceptile: "sep tile",
  poochyena: "pooch yee nah",
  mightyena: "might yee nah",
  linoone: "li noon",
  sableye: "say bul eye",
  mawile: "may while",
  gardevoir: "gar duh vwar",
  electrike: "ee lek trike",
  plusle: "ploo sul",
  minun: "my nun",
  carvanha: "car vah nuh",
  altaria: "al tar ee uh",
  kecleon: "kek lee on",
  chimecho: "chime eh ko",
  regirock: "reh jee rock",
  regice: "reh jice",
  registeel: "reh jee steel",
  latias: "la tee us",
  latios: "la tee os",
  kyogre: "kai oh ger",
  groudon: "grow don",
  deoxys: "dee ox iss",

  // Sinnoh.
  budew: "boo dew",
  pachirisu: "pa chee ree soo",
  buizel: "bwee zul",
  mismagius: "miss may jus",
  electivire: "ee lek ti vire",
  gallade: "guh lade",
  dusknoir: "dusk nwar",
  uxie: "yook see",
  regigigas: "reh jee gie gus",
  giratina: "geer uh tee nuh",
  cresselia: "cress eh lee uh",
  phione: "fee oh nee",
  darkrai: "dark rye",
  arceus: "ar see us",
  lucario: "loo car ee oh",

  // Unova.
  sigilyph: "sig il iff",
  cofagrigus: "kof uh gree gus",
  tirtouga: "tir too gah",
  zorua: "zoh roo ah",
  zoroark: "zoh roh ark",
  reuniclus: "ree yoo nih klus",
  alomomola: "al oh moh moh lah",
  elgyem: "el jee em",
  beheeyem: "be hee em",
  chandelure: "chan del yoor",
  bouffalant: "boo fuh lahnt",
  hydreigon: "hi dry gon",
  volcarona: "vol kuh roh nuh",
  cobalion: "co bay lee on",
  terrakion: "ter ah kee on",
  virizion: "vi riz ee on",
  kyurem: "kyur em",
  genesect: "jen eh sect",

  // Kalos.
  braixen: "brake sen",
  furfrou: "fur froo",
  xerneas: "zur nee us",
  yveltal: "ee vell tahl",
  zygarde: "zy gard",
  diancie: "die an see",

  // Alola.
  mareanie: "mar ee nee",
  tsareena: "zar ee nah",
  pyukumuku: "pyoo koo moo koo",
  togedemaru: "to geh de ma roo",
  mimikyu: "mee mee kyoo",
  dhelmise: "del mize",
  nihilego: "ni hil eh go",
  pheromosa: "fer uh moh sah",
  xurkitree: "zur ki tree",
  necrozma: "neh kroz muh",
  magearna: "muh gear nah",
  naganadel: "na ga nay del",
  blacephalon: "blay sef uh lon",
  zeraora: "zer ay or ah",

  // Galar / Hisui.
  sinistea: "sin is tay ah",
  polteageist: "polt ur geist",
  perrserker: "per sur ker",
  runerigus: "roon er ih gus",
  eiscue: "ice kyoo",
  zacian: "zah shee an",
  zamazenta: "zah muh zen tuh",
  regieleki: "reh jee eh lek ee",
  regidrago: "reh jee dray go",
  wyrdeer: "wur deer",
  basculegion: "bas kyu lee jun",

  // Paldea.
  fuecoco: "fway co co",
  fidough: "fye doh",
  armarouge: "ar muh rooj",
  ceruledge: "ser u lej",
  grafaiai: "gruh fie eye",
  toedscool: "toad skool",
  toedscruel: "toad skroo el",
  gimmighoul: "gim ee gool",
};

export function pronunciationFor(name: string): string {
  const override = OVERRIDES[name.toLowerCase()];
  return override ?? name;
}
