/**
 * renderWithIntl - shared test helper for components that call useTranslations().
 *
 * Any component that calls `useTranslations()` requires a
 * `<NextIntlClientProvider>` ancestor. Without one it throws during render.
 * This helper wraps the component under test in the provider, backed by the
 * real message catalogues from `messages/<locale>.json`, so tests exercise the
 * same translation keys the app uses in production.
 *
 * Usage:
 *
 *   import { renderWithIntl, renderJa, screen } from
 *     "@/components/test-utils/renderWithIntl";
 *
 *   it("renders the practice label in Japanese", () => {
 *     renderJa(<MyComponent />);
 *     expect(screen.getByText("練習")).toBeInTheDocument();
 *   });
 *
 * Re-exports testing utilities from @testing-library/react (excluding `render`)
 * so importers only need one import line.
 */

import React from "react";
import { render } from "@testing-library/react";
import type { RenderOptions, RenderResult } from "@testing-library/react";
import { NextIntlClientProvider } from "next-intl";
import type { AppLocale } from "@/i18n/locales";

// Import all four catalogues statically so vitest can resolve them without
// dynamic-import overhead. TypeScript resolves JSON imports as typed objects
// when `resolveJsonModule: true` is set in tsconfig.json (it is).
import enMessages from "@/messages/en.json";
import jaMessages from "@/messages/ja.json";
import zhHansMessages from "@/messages/zh-Hans.json";
import zhHantMessages from "@/messages/zh-Hant.json";
// Pseudo-locale for the English-leak harness (#1405). Every leaf string in
// en.json is wrapped in sentinel brackets ("[Practice]") so that any text
// node surviving a render-under-xx-pseudo test without brackets is an
// untranslated English string. Generated by scripts/generate-pseudo-locale.mjs.
import xxPseudoMessages from "@/messages/xx-pseudo.json";

// ---------------------------------------------------------------------------
// Internal catalogue map
// ---------------------------------------------------------------------------

/**
 * "xx-pseudo" is a synthetic locale used only in the i18n-leak test harness.
 * It is not a real supported app locale (not in SUPPORTED_LOCALES / AppLocale)
 * but NextIntlClientProvider accepts any string as a locale tag, which is
 * sufficient for the jsdom-render harness.
 */
export type TestLocale = AppLocale | "xx-pseudo";

const MESSAGES: Record<TestLocale, object> = {
  en: enMessages,
  ja: jaMessages,
  "zh-Hans": zhHansMessages,
  "zh-Hant": zhHantMessages,
  "xx-pseudo": xxPseudoMessages,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface IntlRenderOptions extends Omit<RenderOptions, "wrapper"> {
  locale?: TestLocale;
}

/**
 * Renders `ui` inside a `<NextIntlClientProvider>` populated with the real
 * message catalogue for `locale` (default: `"en"`). Returns the same object
 * that `@testing-library/react`'s `render` returns.
 */
export function renderWithIntl(
  ui: React.ReactElement,
  { locale = "en", ...options }: IntlRenderOptions = {},
): RenderResult {
  const messages = MESSAGES[locale as TestLocale];

  // Locale is fixed at render time; `rerender` inherits it and cannot change locale mid-test.
  function Wrapper({ children }: { children: React.ReactNode }) {
    return (
      <NextIntlClientProvider locale={locale} messages={messages}>
        {children}
      </NextIntlClientProvider>
    );
  }

  return render(ui, { wrapper: Wrapper, ...options });
}

/**
 * Convenience shorthand - renders `ui` in the Japanese locale.
 * Satisfies the mandatory non-English locale test requirement.
 */
export function renderJa(ui: React.ReactElement): RenderResult {
  return renderWithIntl(ui, { locale: "ja" });
}

/**
 * Convenience shorthand - renders `ui` in the Simplified Chinese locale.
 * Satisfies the mandatory non-English locale test requirement.
 */
export function renderZhHans(ui: React.ReactElement): RenderResult {
  return renderWithIntl(ui, { locale: "zh-Hans" });
}

/**
 * Convenience shorthand - renders `ui` in the Traditional Chinese locale.
 * Satisfies the mandatory non-English locale test requirement.
 */
export function renderZhHant(ui: React.ReactElement): RenderResult {
  return renderWithIntl(ui, { locale: "zh-Hant" });
}

/**
 * Convenience shorthand - renders `ui` in the pseudo-locale ("xx-pseudo").
 *
 * Use in *.i18n-leak.test.tsx files to verify that all visible text nodes
 * are routed through the message catalogue (sentinel "[...]" wrapping) rather
 * than hard-coded English strings.  See scripts/generate-pseudo-locale.mjs
 * and scripts/i18n-leak-allowlist.ts for details (#1405).
 */
export function renderPseudo(ui: React.ReactElement): RenderResult {
  return renderWithIntl(ui, { locale: "xx-pseudo" });
}

// ---------------------------------------------------------------------------
// Re-export @testing-library/react so callers only need one import line.
//
// We explicitly list every name we re-export and deliberately EXCLUDE
// `render`. Blanket `export *` would let a consumer write:
//
//   import { render } from "@/components/test-utils/renderWithIntl";
//
// and silently get the unwrapped, provider-free render - the footgun this
// helper exists to prevent. Use `renderWithIntl` or `renderJa` instead.
// ---------------------------------------------------------------------------

export {
  screen,
  fireEvent,
  waitFor,
  waitForElementToBeRemoved,
  within,
  act,
  cleanup,
  renderHook,
  // Query helpers - exposed so callers can destructure from their own
  // `renderWithIntl(...)` result and also use the bound queries off `screen`.
  getByRole,
  getByText,
  getByLabelText,
  getByPlaceholderText,
  getByAltText,
  getByTestId,
  getByTitle,
  getByDisplayValue,
  getAllByRole,
  getAllByText,
  getAllByLabelText,
  getAllByPlaceholderText,
  getAllByAltText,
  getAllByTestId,
  getAllByTitle,
  getAllByDisplayValue,
  queryByRole,
  queryByText,
  queryByLabelText,
  queryByPlaceholderText,
  queryByAltText,
  queryByTestId,
  queryByTitle,
  queryByDisplayValue,
  queryAllByRole,
  queryAllByText,
  queryAllByLabelText,
  queryAllByPlaceholderText,
  queryAllByAltText,
  queryAllByTestId,
  queryAllByTitle,
  queryAllByDisplayValue,
  findByRole,
  findByText,
  findByLabelText,
  findByPlaceholderText,
  findByAltText,
  findByTestId,
  findByTitle,
  findByDisplayValue,
  findAllByRole,
  findAllByText,
  findAllByLabelText,
  findAllByPlaceholderText,
  findAllByAltText,
  findAllByTestId,
  findAllByTitle,
  findAllByDisplayValue,
  // Utilities
  prettyDOM,
  logDOM,
  getDefaultNormalizer,
  configure,
  getConfig,
} from "@testing-library/react";
