"use client";

import { useState } from "react";
import type { DailySummaryParts } from "@/lib/review/share";
import { generateDailyShareImage } from "@/lib/share/generateShareImage";

type Props = {
  /** Summary parts used to render the image card and, via `text`, the plain-text fallback. */
  parts: DailySummaryParts;
  /** Pre-formatted summary text — generated by `formatDailySummary`. Used as plain-text fallback. */
  text: string;
};

/**
 * "Share today" button. Priority order:
 *   1. Web Share API file share (PNG image card) — when navigator.canShare({ files }) is truthy.
 *   2. Web Share API text share — when navigator.share is available but file-share is not.
 *   3. PNG download — when the image rendered but the Share API is unavailable.
 *   4. Clipboard text copy — last resort.
 *
 * Never shows raw card content — the parent is responsible for generating
 * spoiler-safe data.
 */
export function ShareTodayButton({ parts, text }: Props) {
  const [status, setStatus] = useState<"idle" | "copied" | "error">("idle");

  async function handleShare() {
    setStatus("idle");

    // Try to render the image card first.
    const blob = await generateDailyShareImage(parts).catch(() => null);
    const file =
      blob !== null
        ? new File([blob], "poke-memory.png", { type: "image/png" })
        : null;

    const nav = typeof navigator !== "undefined" ? navigator : null;

    // --- Path 1: Web Share API with PNG file ---
    if (file !== null && nav !== null) {
      const navExt = nav as Navigator & {
        canShare?: (data: unknown) => boolean;
        share?: (data: { files: File[] }) => Promise<void>;
      };
      if (
        typeof navExt.canShare === "function" &&
        navExt.canShare({ files: [file] }) &&
        typeof navExt.share === "function"
      ) {
        try {
          await navExt.share({ files: [file] });
          return;
        } catch {
          // Share sheet dismissed or unavailable — fall through.
        }
      }
    }

    // --- Path 2: Web Share API text only ---
    if (nav !== null) {
      const navExt = nav as Navigator & {
        share?: (data: { text: string }) => Promise<void>;
      };
      if (typeof navExt.share === "function") {
        try {
          await navExt.share({ text });
          return;
        } catch {
          // Share sheet dismissed or unavailable — fall through.
        }
      }
    }

    // --- Path 3: PNG download ---
    if (file !== null && blob !== null && typeof document !== "undefined") {
      try {
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "poke-memory.png";
        a.click();
        setTimeout(() => URL.revokeObjectURL(url), 0);
        return;
      } catch {
        // Fall through to clipboard.
      }
    }

    // --- Path 4: Clipboard text copy ---
    if (nav === null || !nav.clipboard) {
      setStatus("error");
      setTimeout(() => setStatus("idle"), 2000);
      return;
    }
    try {
      await nav.clipboard.writeText(text);
      setStatus("copied");
      setTimeout(() => setStatus("idle"), 2000);
    } catch {
      setStatus("error");
      setTimeout(() => setStatus("idle"), 2000);
    }
  }

  return (
    <div className="flex flex-col items-center gap-2">
      <button
        type="button"
        onClick={handleShare}
        className="rounded-lg bg-foreground px-5 py-2 text-sm font-semibold text-background transition-colors hover:opacity-80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-foreground focus-visible:ring-offset-2"
      >
        Share today
      </button>
      {status === "copied" ? (
        <p className="text-xs text-zinc-500 dark:text-zinc-400" role="status">
          Copied to clipboard
        </p>
      ) : null}
      {status === "error" ? (
        <p className="text-xs text-rose-600 dark:text-rose-400" role="status">
          Couldn&apos;t copy. Please try again.
        </p>
      ) : null}
    </div>
  );
}
