"use client";

import { useState } from "react";

type Props = {
  /** Pre-formatted summary text — generated by `formatDailySummary`. */
  text: string;
};

/**
 * "Share today" button. Uses Web Share API on mobile (synchronous user
 * gesture) and falls back to writing to the clipboard with a transient
 * confirmation on desktop. Never shows raw card content — the parent
 * is responsible for generating spoiler-safe text.
 */
export function ShareTodayButton({ text }: Props) {
  const [status, setStatus] = useState<"idle" | "copied" | "error">("idle");

  async function handleShare() {
    setStatus("idle");
    const canShare =
      typeof navigator !== "undefined" &&
      typeof (navigator as Navigator & { share?: unknown }).share === "function";
    if (canShare) {
      try {
        await (navigator as Navigator & {
          share: (data: { text: string }) => Promise<void>;
        }).share({ text });
        return;
      } catch {
        // Share sheet dismissed or unavailable; fall through to clipboard.
      }
    }
    try {
      await navigator.clipboard.writeText(text);
      setStatus("copied");
      setTimeout(() => setStatus("idle"), 2000);
    } catch {
      setStatus("error");
      setTimeout(() => setStatus("idle"), 2000);
    }
  }

  return (
    <div className="flex flex-col items-center gap-2">
      <button
        type="button"
        onClick={handleShare}
        className="rounded-lg bg-foreground px-5 py-2 text-sm font-semibold text-background transition-colors hover:opacity-80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-foreground focus-visible:ring-offset-2"
      >
        Share today
      </button>
      {status === "copied" ? (
        <p className="text-xs text-zinc-500 dark:text-zinc-400" role="status">
          Copied to clipboard
        </p>
      ) : null}
      {status === "error" ? (
        <p className="text-xs text-rose-600 dark:text-rose-400" role="status">
          Couldn&apos;t copy — please try again.
        </p>
      ) : null}
    </div>
  );
}
