/**
 * Badge artwork rendering constants (#831).
 *
 * Badge medallions are 17 self-hosted 8-bit pixel-art PNGs under
 * `public/badges/<id>.png`, generated by `tools/art/` (see `tools/art/README.md`
 * for the regeneration pipeline). They are a distinct asset class from the
 * PokéAPI Pokémon sprites documented in `docs/sprites.md`:
 *
 * - Not part of the `GENERATED_SPRITE_WIDTHS` / static-WebP pipeline in
 *   `lib/sprites/` - that pipeline exists to serve ~1025 Pokémon sprites at
 *   multiple responsive widths. There are only 17 badges, each rendered at
 *   one fixed size everywhere it appears, so a multi-width variant set buys
 *   nothing.
 * - Still rendered with `next/image` (the repo default) and a single named
 *   size constant, per the "never inline a pixel literal" rule.
 */

/**
 * Render width (and height) in CSS px for a badge medallion in the Journey
 * page's gym-badge gallery (`BadgeGalleryCard`). Matches the 40 px circle the
 * artwork replaced.
 */
export const BADGE_ICON_SIZE = 40;

/** Public path to a badge's artwork PNG, keyed by the badge's catalog id. */
export function badgeArtworkSrc(badgeId: string): string {
  return `/badges/${badgeId}.png`;
}
