import coreData from "@/lib/pokemon/generated-core.json";
import chainsData from "@/lib/pokemon/generated-chains.json";
import type { EvolutionDetail } from "@/lib/pokemon/triggers";
import { triggerPhrase } from "@/lib/pokemon/triggers";
import type { FormCategory } from "@/lib/pokemon/forms";
import {
  EVOLUTION_ID_OFFSET,
  EDGE_ID_BASE,
  REVERSE_ID_OFFSET,
  REVERSE_EDGE_ID_BASE,
  CRY_ID_OFFSET,
  reverseEdgeIdFor,
  isReverseEdgeId,
} from "@/lib/pokemon/seed-constants";

// ---------------------------------------------------------------------------
// Multi-locale name types (data-layer foundation for #1259).
// UI gating and rendering are handled by the `languages` Labs flag (#1260).
// ---------------------------------------------------------------------------

/**
 * Supported Pokemon name locales.
 *
 * - `en` - English (canonical; always present)
 * - `ja` - Japanese (kanji + kana form from PokéAPI `ja`)
 * - `zh-Hans` - Simplified Chinese
 * - `zh-Hant` - Traditional Chinese
 */
export type PokemonNameLocale = "en" | "ja" | "zh-Hans" | "zh-Hant";

/**
 * Locales that have a transliteration aid.
 * - `ja` - rōmaji (sourced from PokéAPI `ja-roma`)
 * - `zh-Hans` - pinyin (generated by pinyin-pro at seed time)
 * - `zh-Hant` - pinyin (generated by pinyin-pro at seed time)
 */
export type TransliterationLocale = "ja" | "zh-Hans" | "zh-Hant";

/**
 * Per-species locale name entry stored in the sidecar
 * `generated-locale-names.json` / served from
 * `public/pokemon-data/generated-locale-names.json`.
 *
 * Only present for the default form of each species (isDefaultForm = true).
 * Alternate forms share their species' names.
 *
 * Fields are optional at the TypeScript level so payloads built before #1259
 * continue to validate; consumers should treat missing values as the English
 * name fallback.
 */
export type PokemonLocaleNames = {
  /** PokéAPI species ID (matches SeedPokemon.speciesId). */
  speciesId: number;
  /** Name in each supported locale. */
  nameByLocale: Record<PokemonNameLocale, string>;
  /**
   * Transliteration aid in Latin script for non-Latin locales.
   * rōmaji for `ja`; pinyin with tone marks for `zh-Hans` / `zh-Hant`.
   */
  transliterationByLocale: Record<TransliterationLocale, string>;
};

export type { EvolutionDetail };

/**
 * A single Pokédex flavour-text entry with provenance.
 * Added in #1559 - each entry carries the normalised text plus the list of
 * PokéAPI version slugs (e.g. `["red", "blue"]`) whose dex used that text.
 */
export type FlavorTextEntry = {
  text: string;
  versions: string[];
};

export type EvolutionNode = {
  speciesId: number;
  name: string;
  evolvesFromId: number | null;
  // `detail` and `edgeId` are populated by the seed script for edges where
  // evolvesFromId !== null. Roots have detail=null and no edgeId. Both fields
  // are optional in the type so persisted name/reverse cards (which strip
  // evolutionChain on save and re-hydrate from seed on load) continue to
  // validate even when reading older payloads.
  detail?: EvolutionDetail | null;
  edgeId?: number;
};

export type PokemonStats = {
  hp: number;
  attack: number;
  defense: number;
  specialAttack: number;
  specialDefense: number;
  speed: number;
};

export type { FormCategory };

export type SeedPokemon = {
  id: number;
  /**
   * The PokéAPI species ID. For default forms, speciesId === id. For
   * alternate forms (e.g. Alolan Raichu, id=10100), speciesId is the base
   * species ID (26 for Raichu). Added in #445.
   */
  speciesId: number;
  /**
   * True for the primary variety of a species (varieties[0]). False for all
   * alternate forms. Added in #445.
   */
  isDefaultForm: boolean;
  /**
   * Broad category used for future scope-toggle filtering. Added in #445.
   * - "default" - the base form of a species
   * - "regional" - Alolan/Galarian/Hisuian/Paldean variant
   * - "mega" - Mega Evolution (excluded from v1 scope, is_battle_only)
   * - "gmax" - Gigantamax (excluded from v1 scope, is_battle_only)
   * - "primal" - Primal Reversion (excluded from v1 scope, is_battle_only)
   * - "forme" - other out-of-battle forme (Rotom, Deoxys, Ogerpon, etc.)
   */
  formCategory: FormCategory;
  /**
   * The PokéAPI form_name slug, or null for default forms.
   * Examples: "alola", "galar", "mega-x", "gmax", "heat" (Rotom).
   * Added in #445.
   */
  formSlug: string | null;
  /**
   * Human-readable display name. For default forms this is the canonical
   * species name (e.g. "Raichu"). For alternate forms this comes from
   * pokemon-form.names[] (English), falling back to title-cased slug
   * (e.g. "Alolan Raichu"). Added in #445.
   */
  displayName: string;
  name: string;
  spriteUrl: string;
  types: string[];
  stats: PokemonStats;
  flavorText: string;
  /**
   * Lazy-loaded flavour text entries from `generated-flavor.json`.
   * Each entry carries the text and the list of PokéAPI version slugs that
   * used it. `undefined` when the sidecar has not yet loaded (runtime seed).
   * Plain `string[]` shape is retained here for older payloads that pre-date
   * #1559 - `facts.ts` normalises both shapes at read time.
   */
  flavorTexts: FlavorTextEntry[] | string[] | undefined;
  evolutionChain: EvolutionNode[];
  height: number | null;
  weight: number | null;
  baseExperience: number | null;
  genus: string | null;
  generation: string | null;
  captureRate: number | null;
  baseHappiness: number | null;
  growthRate: string | null;
  habitat: string | null;
  genderRate: number | null;
  isLegendary: boolean;
  isMythical: boolean;
  cryUrl: string | null;
  /**
   * PokéAPI version-group slugs whose pokedex includes this species/form.
   * Sorted, deduplicated. Empty array is only used as a defensive fallback -
   * after `scripts/seed-version-groups.mjs` runs every entry has at least one
   * version-group.
   *
   * For regional alternate forms (Alolan/Galarian/Hisuian/Paldean) the list is
   * narrowed to version-groups whose pokedex matches the regional prefix, so
   * Alolan Raichu's list contains only sun-moon and ultra-sun-ultra-moon, not
   * every dex Raichu the species appears in.  Non-regional formes (Rotom
   * appliances, Deoxys formes, etc.) share the default species' membership.
   *
   * Optional at the TypeScript level so persisted scopes / seeds built before
   * #1089 continue to validate; consumers should treat a missing value as an
   * empty array.
   */
  versionGroups?: string[];
};

// ---------------------------------------------------------------------------
// Card types
// ---------------------------------------------------------------------------

// One card per (preEvo, postEvo) edge, with the trigger interpolated into the
// prompt. Branching pre-evolutions (Eevee → 8 forms) produce 8 cards, one per
// branch - each card is independently gradeable and the trigger is the
// gradable signal.
export type EvolutionCard = {
  cardType: "evolution";
  id: number;          // stable edge ID in [1_500_001, 1_999_999); allocated by seed script
  preEvoId: number;
  preEvoName: string;
  preEvoSpriteUrl: string;
  postEvoId: number;
  postEvoName: string;
  postEvoSpriteUrl: string;
  // Natural-English suffix appended after "What does {preEvoName} evolve into".
  // Null for edges whose trigger shape we don't recognise - caller falls back
  // to the bare "?" prompt.
  triggerPhrase: string | null;
};

// One reverse-evolution card per forward edge - same edge data, different ID,
// rendered with the prompt direction flipped ("Which Pokémon evolves into X
// via Y?"). The trigger phrase is reused as-is; the rendering layer reads the
// id namespace to choose the prompt + answer sides.
export type ReverseEvolutionCard = Omit<EvolutionCard, "cardType"> & {
  cardType: "reverse-evolution";
};

/**
 * The three seed arrays produced from core + chains data.
 * Returned by `buildSeed` and cached by `seed-async.ts`.
 */
export type SeedData = {
  seedPokemon: readonly SeedPokemon[];
  seedEvolutionCards: readonly EvolutionCard[];
  seedReverseEvolutionCards: readonly ReverseEvolutionCard[];
};

// ---------------------------------------------------------------------------
// Re-export constants and helpers from seed-constants.ts so every existing
// import site (`import { EDGE_ID_BASE } from "@/lib/pokemon/seed"`) continues
// to work without modification.
// ---------------------------------------------------------------------------

export {
  EVOLUTION_ID_OFFSET,
  EDGE_ID_BASE,
  REVERSE_ID_OFFSET,
  REVERSE_EDGE_ID_BASE,
  CRY_ID_OFFSET,
  reverseEdgeIdFor,
  isReverseEdgeId,
};

// ---------------------------------------------------------------------------
// Internal helper types for raw JSON shapes
// ---------------------------------------------------------------------------

type ChainsPayload = {
  chains: Record<string, EvolutionNode[]>;
  pokemonChain: Record<string, string>;
};

// ---------------------------------------------------------------------------
// buildSeed - pure function; no module-level side-effects
// ---------------------------------------------------------------------------

/**
 * Build the three seed arrays from raw JSON payloads.
 *
 * This is the canonical logic for constructing `SEED_POKEMON`,
 * `SEED_EVOLUTION_CARDS`, and `SEED_REVERSE_EVOLUTION_CARDS`.  It is a pure
 * function so that both the synchronous (static-import) path in this module
 * and the async (fetch) path in `seed-async.ts` can share it without
 * duplicating logic.
 *
 * @param rawCoreData - Parsed content of `generated-core.json`.
 * @param rawChainsData - Parsed content of `generated-chains.json`.
 */
export function buildSeed(
  rawCoreData: unknown,
  rawChainsData: unknown,
): SeedData {
  // --- reconstruct SEED_POKEMON ---
  const _chainsPayload = rawChainsData as ChainsPayload;
  const _chainMap = _chainsPayload.chains;
  const _pokemonChainRef = _chainsPayload.pokemonChain;

  const seedPokemon: readonly SeedPokemon[] = (
    rawCoreData as Array<Omit<SeedPokemon, "evolutionChain" | "flavorTexts">>
  ).map((p) => {
    const chainHash = _pokemonChainRef[String(p.id)];
    const evolutionChain: EvolutionNode[] = chainHash
      ? (_chainMap[chainHash] ?? [])
      : [];
    return { ...p, evolutionChain, flavorTexts: undefined } as SeedPokemon;
  });

  // --- reconstruct SEED_EVOLUTION_CARDS ---
  const MAX_NAME_ID = EVOLUTION_ID_OFFSET - 1;
  const seedEvolutionCards: readonly EvolutionCard[] = (() => {
    const cards: EvolutionCard[] = [];
    const seenEdgeIds = new Set<number>();
    const pokemonById = new Map(seedPokemon.map((p) => [p.id, p]));

    for (const pokemon of seedPokemon) {
      if (pokemon.id <= 0 || pokemon.id > MAX_NAME_ID) {
        // Alternate-form IDs (10001+) are outside the name-card namespace and
        // must not produce evolution cards - their evolution edges are carried by
        // the default-form record which shares the same chain. Skip rather than
        // throwing so the seed can include forms without breaking this builder.
        // Form-aware evolution cards are #447/#448.
        continue;
      }
      for (const node of pokemon.evolutionChain) {
        if (node.evolvesFromId !== pokemon.id) continue;
        const edgeId = node.edgeId;
        if (typeof edgeId !== "number") {
          throw new Error(
            `Chain edge ${pokemon.name} → ${node.name} is missing an edgeId. Re-run \`npm run seed\` so scripts/seed-pokemon.mjs can allocate stable edge IDs.`,
          );
        }
        if (edgeId <= EDGE_ID_BASE || edgeId >= REVERSE_ID_OFFSET) {
          throw new Error(
            `Edge ID ${edgeId} (${pokemon.name} → ${node.name}) outside reserved sub-range [${EDGE_ID_BASE + 1}, ${REVERSE_ID_OFFSET - 1}].`,
          );
        }
        if (seenEdgeIds.has(edgeId)) continue;
        seenEdgeIds.add(edgeId);
        const postEvo = pokemonById.get(node.speciesId);
        if (!postEvo) {
          throw new Error(
            `Edge ${pokemon.name} → ${node.name} (speciesId ${node.speciesId}) has no matching pokemon in seed data - seed may be incomplete.`,
          );
        }
        cards.push({
          cardType: "evolution",
          id: edgeId,
          preEvoId: pokemon.id,
          preEvoName: pokemon.name,
          preEvoSpriteUrl: pokemon.spriteUrl,
          postEvoId: postEvo.id,
          postEvoName: postEvo.name,
          postEvoSpriteUrl: postEvo.spriteUrl,
          triggerPhrase: triggerPhrase(node.detail ?? null),
        });
      }
    }
    return cards;
  })();

  // --- reconstruct SEED_REVERSE_EVOLUTION_CARDS ---
  const seedReverseEvolutionCards: readonly ReverseEvolutionCard[] =
    seedEvolutionCards.map((fwd) => ({
      ...fwd,
      cardType: "reverse-evolution" as const,
      id: reverseEdgeIdFor(fwd.id),
    }));

  return { seedPokemon, seedEvolutionCards, seedReverseEvolutionCards };
}

// ---------------------------------------------------------------------------
// Synchronous module-level exports (existing public API - unchanged)
// ---------------------------------------------------------------------------

// Reconstruct the full SeedPokemon array by joining the core data with the
// deduplicated evolution chains. Each Pokémon in generated-core.json omits
// `flavorTexts` and `evolutionChain` to reduce the bundled JS chunk size
// (~1.2 MB bundled vs ~2.9 MB with both fields inline). The chain for each
// Pokémon is resolved from the compact chains map in generated-chains.json.
// `flavorTexts` stays absent from the runtime SEED_POKEMON (it is
// `FlavorTextEntry[] | string[] | undefined`); the facts panel loads it lazily
// via `loadFlavorTexts()` in `lib/pokemon/facts.ts`.

const _built = buildSeed(coreData, chainsData);

export const SEED_POKEMON: readonly SeedPokemon[] = _built.seedPokemon;
export const SEED_EVOLUTION_CARDS: readonly EvolutionCard[] =
  _built.seedEvolutionCards;
export const SEED_REVERSE_EVOLUTION_CARDS: readonly ReverseEvolutionCard[] =
  _built.seedReverseEvolutionCards;
