import { NextResponse } from "next/server";
import { timingSafeEqual } from "node:crypto";
import { createClient as createSupabaseAdminClient } from "@supabase/supabase-js";
import webpush from "web-push";
import { todayInTimezone } from "@/lib/utils/format-date";
import { isCardEligible } from "@/lib/eligibility";

/**
 * Daily Web Push reminder route (#1056).
 *
 * Triggered by the `web-push-daily-reminders` pg_cron job (migration 028)
 * via `net.http_post` with a Bearer header carrying the
 * `cron_shared_secret` Vault value. The job fires once per day at 08:00
 * UTC; this handler then fans out per-user Web Push notifications for
 * every `push_subscriptions` row whose owning user has at least one card
 * due today in their own timezone.
 *
 * Why a route handler instead of a Supabase Edge Function: VAPID JWTs are
 * ECDSA P-256 (ES256) and pgcrypto / pgsodium can't produce that shape, so
 * the cron call has to land somewhere with a real crypto stack. Keeping
 * this in the Next.js codebase means one deploy pipeline, one set of env
 * vars, and one place to test the auth + payload encryption logic.
 *
 * AUTH MODEL
 *   1. Caller authenticates via `Authorization: Bearer <CRON_SHARED_SECRET>`.
 *      Any other value (or missing header) returns 401. The shared secret
 *      lives in both Vercel env (`CRON_SHARED_SECRET`) and Supabase Vault
 *      (`cron_shared_secret`); they must match exactly.
 *   2. Inside the route, we use the SUPABASE_SERVICE_ROLE_KEY to read
 *      across every user's `push_subscriptions` row. Row-level security is
 *      bypassed by design — the cron has no `auth.uid()` to authorise as,
 *      and the route's only privileged operation is reading subscriptions
 *      + computing due counts + sending pushes.
 */

// Note: this route must run on Node.js (not Edge) because the `web-push`
// package relies on the Node `crypto` module for ES256 JWT signing and
// payload encryption. Next.js 16's Cache Components mode forbids the
// per-route `runtime` segment config, so we rely on the project-wide
// default Node runtime here.

/** JSON shape of the push payload delivered to the SW push handler. */
type PushPayload = {
  title: string;
  body: string;
  url: string;
};

/** Pluralisation helper. Avoids relying on Intl.PluralRules for one word. */
function plural(n: number, singular: string, plural: string): string {
  return n === 1 ? singular : plural;
}

/**
 * Constant-time bearer-header comparison. Plain `===` on the assembled
 * `Bearer <secret>` string leaks the shared secret's length and prefix via
 * the early-exit timing characteristic of JavaScript string equality. We
 * compare equal-length byte buffers via `crypto.timingSafeEqual` instead.
 *
 * The early length check is fine. `timingSafeEqual` REQUIRES both buffers to
 * be the same length (it throws otherwise), and an attacker who learns the
 * fixed-length total (`'Bearer '` + secret) buys nothing actionable since
 * `CRON_SHARED_SECRET` is generated by `openssl rand -base64 32` and so has
 * a constant length per deploy.
 */
function isAuthorized(headerValue: string | null, secret: string): boolean {
  if (!headerValue || !secret) return false;
  const expected = `Bearer ${secret}`;
  if (headerValue.length !== expected.length) return false;
  try {
    return timingSafeEqual(Buffer.from(headerValue), Buffer.from(expected));
  } catch {
    return false;
  }
}

/**
 * Builds the user-facing body string for the daily reminder. Kept pure so
 * we can unit test it without touching the network or DB.
 *
 * British English copy. No em dashes (per AGENTS.md "Punctuation").
 *
 * When `newEstimate` is 0 (or omitted), renders the due count only, e.g.
 * "3 cards due for review." When `newEstimate` is positive, renders a
 * combined count so the user sees the full picture, e.g. "3 due plus 15
 * new ready to practise." Both counts must be positive to use the combined
 * form; a zero due count with new cards only renders "15 new cards ready."
 *
 * The estimate is capped by per-direction daily new-card limits summed
 * across enabled directions — it does not include cards whose `first_seen`
 * is already today (those are cards started during today's session, not
 * "truly new"). It does not account for practice scope (localStorage-only),
 * learning-step state, or `maxReviewsPerDay` caps.
 */
export function buildDailyMessage(dueCount: number, newEstimate: number = 0): PushPayload {
  const title = "Time to practise";
  let body: string;

  if (dueCount > 0 && newEstimate > 0) {
    body =
      `${String(dueCount)} ${plural(dueCount, "card", "cards")} due` +
      ` plus ${String(newEstimate)} new ready to practise.`;
  } else if (dueCount > 0) {
    body = `${String(dueCount)} ${plural(dueCount, "card", "cards")} due for review.`;
  } else {
    body = `${String(newEstimate)} new ${plural(newEstimate, "card", "cards")} ready to practise.`;
  }

  return { title, body, url: "/" };
}

type SubscriptionRow = {
  id: string;
  user_id: string;
  endpoint: string;
  p256dh: string;
  auth_secret: string;
};

/**
 * Subset of the `user_settings` row shape. `settings` is the JSONB blob
 * carrying per-user card-type enabled flags and daily new-card caps.
 * `timezone` is a scalar column (migration 019).
 */
type SettingsRow = {
  user_id: string;
  timezone: string | null;
  settings: Record<string, unknown> | null;
};

/**
 * The per-user eligibility flags extracted from the `settings` JSONB.
 * Mirrors the relevant fields from `UserSettings` in lib/settings/persistence.ts.
 * Defaults match `DEFAULT_SETTINGS` so users with missing/partial JSONB
 * fall back to the same behaviour as the app itself.
 */
type UserEligibility = {
  nameCardsEnabled: boolean;
  evolutionCardsEnabled: boolean;
  reverseEvolutionCardsEnabled: boolean;
  reverseCardsEnabled: boolean;
  cryCardsEnabled: boolean;
  alternateFormsEnabled: boolean;
  maxNewPerDay: number;
  maxNewEvolutionPerDay: number;
  maxNewReversePerDay: number;
  maxNewCryPerDay: number;
};

/** DEFAULT_SETTINGS-aligned fallbacks, used when a JSONB field is missing or invalid. */
const DEFAULT_ELIGIBILITY: UserEligibility = {
  nameCardsEnabled: true,
  evolutionCardsEnabled: true,
  reverseEvolutionCardsEnabled: false,
  reverseCardsEnabled: false,
  cryCardsEnabled: false,
  alternateFormsEnabled: false,
  maxNewPerDay: 10,
  maxNewEvolutionPerDay: 5,
  maxNewReversePerDay: 10,
  maxNewCryPerDay: 10,
};

/**
 * Parse the per-user eligibility settings from the raw JSONB blob. Permissive:
 * a missing or non-boolean field falls back to the DEFAULT_SETTINGS value.
 * Only the fields that affect the daily-push due count are extracted.
 */
function parseEligibility(rawSettings: Record<string, unknown> | null): UserEligibility {
  if (!rawSettings || typeof rawSettings !== "object") return { ...DEFAULT_ELIGIBILITY };
  // Bind to a non-null local so nested functions narrow cleanly.
  const s: Record<string, unknown> = rawSettings;
  function boolField(key: keyof UserEligibility, defaultVal: boolean): boolean {
    const v = s[key];
    return typeof v === "boolean" ? v : defaultVal;
  }
  function numField(key: keyof UserEligibility, defaultVal: number): number {
    const v = s[key];
    return typeof v === "number" && Number.isFinite(v) && v >= 0 ? v : defaultVal;
  }
  return {
    nameCardsEnabled:             boolField("nameCardsEnabled",             DEFAULT_ELIGIBILITY.nameCardsEnabled),
    evolutionCardsEnabled:        boolField("evolutionCardsEnabled",        DEFAULT_ELIGIBILITY.evolutionCardsEnabled),
    reverseEvolutionCardsEnabled: boolField("reverseEvolutionCardsEnabled", DEFAULT_ELIGIBILITY.reverseEvolutionCardsEnabled),
    reverseCardsEnabled:          boolField("reverseCardsEnabled",          DEFAULT_ELIGIBILITY.reverseCardsEnabled),
    cryCardsEnabled:              boolField("cryCardsEnabled",              DEFAULT_ELIGIBILITY.cryCardsEnabled),
    alternateFormsEnabled:        boolField("alternateFormsEnabled",        DEFAULT_ELIGIBILITY.alternateFormsEnabled),
    maxNewPerDay:          numField("maxNewPerDay",          DEFAULT_ELIGIBILITY.maxNewPerDay),
    maxNewEvolutionPerDay: numField("maxNewEvolutionPerDay", DEFAULT_ELIGIBILITY.maxNewEvolutionPerDay),
    maxNewReversePerDay:   numField("maxNewReversePerDay",   DEFAULT_ELIGIBILITY.maxNewReversePerDay),
    maxNewCryPerDay:       numField("maxNewCryPerDay",       DEFAULT_ELIGIBILITY.maxNewCryPerDay),
  };
}

/**
 * Returns true when a card row is eligible under the user's settings.
 *
 * Delegates to `isCardEligible` from `lib/eligibility` (#1160), which is
 * the single source of truth shared with the on-device PWA badge filter
 * (`lib/review/scope.ts` `computeEligibleCardIds`).
 *
 * Card-type gates:
 *   - `name`                   → nameCardsEnabled
 *   - `evolution-edge`         → evolutionCardsEnabled
 *   - `reverse-evolution-edge` → reverseEvolutionCardsEnabled
 *   - `reverse`                → reverseCardsEnabled
 *   - `cry`                    → cryCardsEnabled
 *
 * Alt-forms gate (when `alternateFormsEnabled` is false):
 *   - For `name` / `reverse` / `cry` cards, the subject_key is the numeric
 *     species id. Ids >= 10000 are alt-form variants and are excluded.
 *   - For `evolution-edge` / `reverse-evolution-edge` cards, the subject_key
 *     is `"<fromId>>><toId>"`. Exclude if either endpoint id >= 10000.
 *
 * Unknown card_type values pass through so future card types are not
 * silently dropped while we await a route update.
 */
function rowIsEligible(
  cardType: string,
  subjectKey: string,
  eligibility: UserEligibility,
): boolean {
  return isCardEligible({ cardType, subjectKey }, eligibility);
}

/**
 * Compute the capped new-card estimate for a user.
 *
 * For each enabled card direction, the estimate is:
 *   min(maxNewPerDay[direction], maxNewPerDay[direction] - startedTodayCount[direction])
 *
 * `startedTodayCount[direction]` is the count of `card_reviews` rows for
 * this user where `first_seen = today` and the row passes the eligibility
 * gate — i.e. cards the user has already started during today's session.
 * Subtracting these prevents double-counting cards that are new-and-due
 * (first introduced today, due today).
 *
 * The result is floor'd at 0 so a user who has already hit their daily cap
 * contributes 0 to the estimate rather than a negative number.
 *
 * Note: reverse-evolution cards share the evolution daily-limit bucket with
 * forward evolution cards. The estimate sums the caps for both directions
 * independently — a deliberate simplification that may overcount slightly
 * when both are enabled, but is consistent with how `buildSessionQueues`
 * was written at the time of #1153.
 */
function computeNewEstimate(
  startedTodayCounts: Record<string, number>,
  eligibility: UserEligibility,
): number {
  let estimate = 0;

  if (eligibility.nameCardsEnabled) {
    estimate += Math.max(
      0,
      eligibility.maxNewPerDay - (startedTodayCounts["name"] ?? 0),
    );
  }
  if (eligibility.evolutionCardsEnabled) {
    estimate += Math.max(
      0,
      eligibility.maxNewEvolutionPerDay - (startedTodayCounts["evolution-edge"] ?? 0),
    );
  }
  if (eligibility.reverseEvolutionCardsEnabled) {
    estimate += Math.max(
      0,
      eligibility.maxNewEvolutionPerDay - (startedTodayCounts["reverse-evolution-edge"] ?? 0),
    );
  }
  if (eligibility.reverseCardsEnabled) {
    estimate += Math.max(
      0,
      eligibility.maxNewReversePerDay - (startedTodayCounts["reverse"] ?? 0),
    );
  }
  if (eligibility.cryCardsEnabled) {
    estimate += Math.max(
      0,
      eligibility.maxNewCryPerDay - (startedTodayCounts["cry"] ?? 0),
    );
  }

  return estimate;
}

type DueRow = {
  user_id: string;
  card_type: string;
  subject_key: string;
  first_seen: string | null;
};

export async function POST(request: Request) {
  const sharedSecret = process.env.CRON_SHARED_SECRET;
  const vapidPublicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
  const vapidPrivateKey = process.env.VAPID_PRIVATE_KEY;
  const vapidSubject = process.env.VAPID_SUBJECT;
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  // Misconfiguration → 503 (Service Unavailable). 500 would imply a crash
  // worth investigating; 503 conveys "the route is configured wrong" which
  // is the actual state. The cron job retries are bounded by pg_net's
  // own retry policy so this won't loop indefinitely.
  if (
    !sharedSecret ||
    !vapidPublicKey ||
    !vapidPrivateKey ||
    !vapidSubject ||
    !supabaseUrl ||
    !serviceRoleKey
  ) {
    return NextResponse.json(
      { ok: false, error: "misconfigured" },
      { status: 503 },
    );
  }

  // Constant-time bearer check via timingSafeEqual; see isAuthorized above.
  // The 401 response carries no body so we don't reflect anything about the
  // configured route's expectations (header name, endpoint shape) back to an
  // unauthenticated caller. The pg_cron job that triggers the legitimate
  // call doesn't read the response body anyway.
  const authHeader = request.headers.get("authorization");
  if (!isAuthorized(authHeader, sharedSecret)) {
    return new NextResponse(null, { status: 401 });
  }

  webpush.setVapidDetails(vapidSubject, vapidPublicKey, vapidPrivateKey);

  // Service-role client. Bypasses RLS so we can read across all users in
  // a single round-trip. This client must NEVER reach the browser; the
  // route handler is the only consumer.
  const admin = createSupabaseAdminClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  // Step 1: fetch every push subscription. The result fits comfortably in
  // memory at our scale (one row per device per signed-in user).
  const { data: subsData, error: subsError } = await admin
    .from("push_subscriptions")
    .select("id, user_id, endpoint, p256dh, auth_secret");
  if (subsError || !subsData) {
    return NextResponse.json(
      { ok: false, error: "subscriptions_query_failed" },
      { status: 502 },
    );
  }
  const subscriptions = subsData as SubscriptionRow[];
  if (subscriptions.length === 0) {
    return NextResponse.json({ ok: true, sent: 0, deleted: 0 });
  }

  // Step 2: resolve timezones and per-user eligibility settings. We widen
  // the SELECT to include the `settings` JSONB so we can filter by card-type
  // enabled flags and the alt-forms toggle client-side. Users without a
  // stored settings record fall back to DEFAULT_ELIGIBILITY (mirrors
  // DEFAULT_SETTINGS in lib/settings/persistence.ts).
  const uniqueUserIds = Array.from(new Set(subscriptions.map((s) => s.user_id)));
  const { data: settingsData, error: settingsError } = await admin
    .from("user_settings")
    .select("user_id, timezone, settings")
    .in("user_id", uniqueUserIds);
  if (settingsError) {
    return NextResponse.json(
      { ok: false, error: "settings_query_failed" },
      { status: 502 },
    );
  }
  const timezoneByUser = new Map<string, string>();
  const eligibilityByUser = new Map<string, UserEligibility>();
  for (const row of (settingsData ?? []) as SettingsRow[]) {
    if (row.timezone) timezoneByUser.set(row.user_id, row.timezone);
    eligibilityByUser.set(row.user_id, parseEligibility(row.settings));
  }

  // Step 3: bucket users by "today in their timezone" so each distinct
  // calendar date is queried at most once. At our scale this is at most
  // ~30 buckets covering every inhabited UTC offset.
  const usersByDueDate = new Map<string, string[]>();
  for (const userId of uniqueUserIds) {
    const tz = timezoneByUser.get(userId) ?? "UTC";
    const today = todayInTimezone(tz);
    const bucket = usersByDueDate.get(today);
    if (bucket) bucket.push(userId);
    else usersByDueDate.set(today, [userId]);
  }

  // Step 4: per-user due counts and started-today counts in a single
  // round-trip per timezone bucket.
  //
  // We fetch `user_id`, `card_type`, `subject_key`, and `first_seen` for
  // every row that satisfies `due_date <= today AND user_id IN bucket AND
  // hidden_since IS NULL`, then aggregate client-side.
  //
  // For each row we apply the per-user eligibility gate:
  //   - Card-type enable flags (nameCardsEnabled, etc.) from settings JSONB.
  //   - Alt-forms exclusion: when alternateFormsEnabled is false, rows with
  //     subject_key that resolves to an alt-form species id (>= 10000) are
  //     skipped (#1153).
  //
  // Rows where `first_seen = today` are still eligible (they count toward
  // the due total) but also counted in a separate bucket so we can compute
  // the new-card estimate (cards started today reduce the remaining new-card
  // headroom for that direction).
  const dueCountByUser = new Map<string, number>();
  // startedTodayByUser: user_id → { card_type → count }
  const startedTodayByUser = new Map<string, Record<string, number>>();
  for (const [today, userIds] of usersByDueDate) {
    const { data: dueData, error: dueError } = await admin
      .from("card_reviews")
      .select("user_id, card_type, subject_key, first_seen")
      .lte("due_date", today)
      .in("user_id", userIds)
      .is("hidden_since", null);
    if (dueError) {
      return NextResponse.json(
        { ok: false, error: "due_query_failed" },
        { status: 502 },
      );
    }
    for (const row of (dueData ?? []) as DueRow[]) {
      const eligibility = eligibilityByUser.get(row.user_id) ?? DEFAULT_ELIGIBILITY;
      if (!rowIsEligible(row.card_type, row.subject_key, eligibility)) continue;

      dueCountByUser.set(
        row.user_id,
        (dueCountByUser.get(row.user_id) ?? 0) + 1,
      );
      // Track first_seen = today rows per card type so we can subtract them
      // from the new-card estimate (they're already started, not truly new).
      if (row.first_seen === today) {
        if (!startedTodayByUser.has(row.user_id)) {
          startedTodayByUser.set(row.user_id, {});
        }
        const counts = startedTodayByUser.get(row.user_id)!;
        counts[row.card_type] = (counts[row.card_type] ?? 0) + 1;
      }
    }
  }

  // Step 5: send. Dead subscriptions (410 Gone) and not-found (404) are
  // deleted so the next cron run doesn't try them again. All other errors
  // are logged and skipped — a single bad endpoint must not abort the
  // whole batch.
  const toDelete: string[] = [];
  let sent = 0;
  for (const sub of subscriptions) {
    const dueCount = dueCountByUser.get(sub.user_id) ?? 0;
    const eligibility = eligibilityByUser.get(sub.user_id) ?? DEFAULT_ELIGIBILITY;
    const startedTodayCounts = startedTodayByUser.get(sub.user_id) ?? {};
    const newEstimate = computeNewEstimate(startedTodayCounts, eligibility);

    if (dueCount <= 0 && newEstimate <= 0) continue;

    const payload = buildDailyMessage(dueCount, newEstimate);
    try {
      await webpush.sendNotification(
        {
          endpoint: sub.endpoint,
          keys: { p256dh: sub.p256dh, auth: sub.auth_secret },
        },
        JSON.stringify(payload),
      );
      sent++;
    } catch (err: unknown) {
      const status = (err as { statusCode?: number }).statusCode;
      if (status === 404 || status === 410) {
        toDelete.push(sub.id);
        continue;
      }
      // Transient or non-fatal error — keep going so a single bad device
      // does not block the rest of the batch.
      console.warn("[push] sendNotification failed", { id: sub.id, status });
    }
  }

  // Step 6: cleanup. Best-effort — if the delete fails we'll retry on the
  // next cron cycle when the same endpoints fail again.
  let deleted = 0;
  if (toDelete.length > 0) {
    const { error: deleteError, count } = await admin
      .from("push_subscriptions")
      .delete({ count: "exact" })
      .in("id", toDelete);
    if (!deleteError) deleted = count ?? toDelete.length;
  }

  return NextResponse.json({ ok: true, sent, deleted });
}
