import { timingSafeEqual } from "node:crypto";

/**
 * Constant-time bearer-header comparison, shared by every route guarded by
 * `CRON_SHARED_SECRET` (discord/digest, discord/notify, push/send-daily).
 *
 * Plain `===` on the assembled `Bearer <secret>` string leaks the shared
 * secret's length and prefix via the early-exit timing characteristic of
 * JavaScript string equality. We compare equal-length byte buffers via
 * `crypto.timingSafeEqual` instead.
 *
 * The early length check is fine. `timingSafeEqual` REQUIRES both buffers to
 * be the same length (it throws otherwise), and an attacker who learns the
 * fixed-length total (`'Bearer '` + secret) buys nothing actionable since
 * `CRON_SHARED_SECRET` is generated by `openssl rand -base64 32` and so has
 * a constant length per deploy.
 */
export function isAuthorized(
  headerValue: string | null,
  secret: string,
): boolean {
  if (!headerValue || !secret) return false;
  const expected = `Bearer ${secret}`;
  if (headerValue.length !== expected.length) return false;
  try {
    return timingSafeEqual(Buffer.from(headerValue), Buffer.from(expected));
  } catch {
    return false;
  }
}
